reddit:
  client_id: 'YPyzyCmOF8RqJuMiJih5Fg'
  client_secret: 'sPdIj2wQOjXiQUUYytV5bUjpzFPB3A'
  user_agent: 'SC4021 Information Retreival'

scraping:
  subreddits:
    - 'tigerbrokers_official'
    - 'webull'
    - 'TigerBrokers'
  posts_per_subreddit: 50
