services:
  backend:
    build:
      context: ./backend
      dockerfile: ./build/Dockerfile
    ports:
      - "8000:8000"
  
  frontend:
    build:
      context: ./frontend
      dockerfile: ./build/Dockerfile
    ports:
      - "3000:3000"