services:
    # backend:
    #     build:
    #         context: ./backend
    #         dockerfile: ./build/Dockerfile
    #     image: backend
    #     volumes:
    #         - ./backend/models:/models
    #     ports:
    #         - '8000:8000'

    frontend:  
        build:
            context: ./frontend
            dockerfile: ./build/Dockerfile
        image: frontend
        ports:
            - "5173:5173"
    solr:
        image: solr
        ports:
            - '8983:8983'
        volumes:
            - ./indexing/build/solr_config:/opt/solr/server/solr/configsets/myconfig
        command:
            - solr-precreate
            - mycollection
            - /opt/solr/server/solr/configsets/myconfig

    solr-indexer:
        image: curlimages/curl:latest
        depends_on:
            - solr
        volumes:
            - ./indexing/dataset:/data
        entrypoint:
            - sh
            - -c
            - |
              echo "⏳ Waiting for Solr..."; 
              sleep 10;
              echo "🚀 Posting reddit_index.json to Solr...";
              curl -H "Content-Type: application/json" \
                  --data-binary "@/data/reddit_index.json" \
                  "http://solr:8983/solr/mycollection/update?commit=true";
              echo "✅ Done!";

