services:
  backend:
    build:
      context: ./backend
      dockerfile: ./build/Dockerfile
    image: backend
    ports:
      - "8000:8000"
  
  frontend:
    build:
      context: ./frontend
      dockerfile: ./build/Dockerfile
    image: frontend
    ports:
      - "3000:3000"

  solr:
    image: solr
    ports:
      - "8983:8983"
    command:
      - solr-precreate
      - mycollection