services:
  backend:
    build:
      context: ./backend
      dockerfile: ./build/Dockerfile
    image: backend
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
  
  frontend:
    build:
      context: ./frontend
      dockerfile: ./build/Dockerfile
    image: frontend
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"